language: r
sudo: false
cache:
  packages: yes
pandoc_version: 1.19.2.1

env:
  global:
    - PANDOC_VERSION=default
    - PANDOC_VERSION=latest PATH=$HOME/bin:$PATH

before_install:
  - "[[ ${PANDOC_VERSION} = latest ]] && ./install-pandoc.sh || true"
